### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Ghost0159** [ghost-land/GhostEshopWeb#1]
- [ ] Make sure that the size of the games varies according to the version

- [ ] Put a button to download the game with the direct link (the link should be a temporary link)

- [ ] Game images (screenshots...)

- [ ] Improving the display of the games section

- [ ] At the bottom of the site should be added an icon leading to the wiki: https://wiki.ghosteshop.com/

- [ ] Also a button leading to the RSS feed: https://ghosteshop.com/feed/news.xml

- [ ] And a button to the script: https://cdn.ghosteshop.com/script/ghosteshop.json

- [ ] And finally, another button leading to the twitter: https://twitter.com/GhosteShop

**Comment by Ghost0159** [comment]
- [ ] Complete overhaul of the games part of the site (https://ghosteshop.com/games)

**Comment by Ghost0159** [comment]
Adding Languages :
- [ ] Spanish
- [ ] Japanese

**Comment by Ghost0159** [comment]
- [ ] Add a game page for Ghost eShop DS
- [ ] Add a button to see the qrcode, next to the one to download the Ghost eShop homebrew on the main page of the website
